# Generated by Django 2.0.1 on 2018-01-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeNewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('newsText', models.CharField(max_length=2000)),
                ('sourceName', models.CharField(default='null', max_length=100)),
                ('sourceURL', models.CharField(default='null', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
